#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/pip ]; then
  echo "Running Custom installation of Python-Pip and modules"
  apt update
  apt install -Y python3-pip
  pip install --no-cache-dir -U \
    apprise \
    chardet \
    pynzbget
fi

if [ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    python3 \
    python3-pip 
fi
if [ -f /sbin/apk ]; then
  # Alpine
  apk add --no-cache \
    py3-pip \
    python3 
fi
pip3 install pyunpack