#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    patool \
    gcc \
    python3 \
    python3-setuptools \
    python3-wheel \
    libpython3-dev \
    python3-pip 
fi
if [ -f /sbin/apk ]; then
  # Alpine
  apk add --no-cache \
    gcc \
    py3-pip \
    py3-setuptools \
    py3-wheel \
    python3 \
    python3-dev
fi
pip3 install pyunpack requests reflink
